name: dotnet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore Generator/Generator.csproj

    - name: Build
      run: dotnet build Generator/Generator.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test Generator/Generator.csproj --no-restore --verbosity normal
